// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextPlay.Api.Infrastructure.Ef;

#nullable disable

namespace NextPlay.Api.Migrations
{
    [DbContext(typeof(NextPlayDbContext))]
    [Migration("20260603040551_RemoveSteamIntegration")]
    partial class RemoveSteamIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("NextPlay.Api.Domain.Entities.Game", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementsTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementsUnlocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ControllerFriendly")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgIconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgLogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AppId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NextPlay.Api.Domain.Entities.Hltb", b =>
                {
                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompletionistMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MainExtraMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MainMin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AppId");

                    b.ToTable("Hltbs");
                });

            modelBuilder.Entity("NextPlay.Api.Domain.Entities.Scores", b =>
                {
                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Metacritic")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OpenCritic")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SteamNegative")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SteamPositive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SteamPositivePct")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AppId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("NextPlay.Api.Domain.Entities.Hltb", b =>
                {
                    b.HasOne("NextPlay.Api.Domain.Entities.Game", "Game")
                        .WithOne("Hltb")
                        .HasForeignKey("NextPlay.Api.Domain.Entities.Hltb", "AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NextPlay.Api.Domain.Entities.Scores", b =>
                {
                    b.HasOne("NextPlay.Api.Domain.Entities.Game", "Game")
                        .WithOne("Scores")
                        .HasForeignKey("NextPlay.Api.Domain.Entities.Scores", "AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NextPlay.Api.Domain.Entities.Game", b =>
                {
                    b.Navigation("Hltb");

                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
